'use strict';

const { generateCI } = require('./templates/ci');
const { generateDeployStaging } = require('./templates/deploy-staging');
const { generateDeployProduction } = require('./templates/deploy-production');
const { generateEnvExample } = require('./templates/env-example');

/**
 * Main entry point.
 * @param {object} config
 * @param {string} config.projectType      - nextjs | react | nodejs | laravel | wordpress | shopify-theme | nestjs
 * @param {string} config.packageManager   - npm | yarn | pnpm
 * @param {string} config.deployTarget     - vercel | render | aws | digitalocean | vps
 * @param {string} config.branchFlow       - dev-staging-main | feature-main
 * @param {string[]} config.checks         - lint | typecheck | test | build | lighthouse | playwright
 * @param {string[]} config.deployEnvironments - staging | production | both
 * @returns {object} Map of relative file paths → file content strings
 */
function generateWorkflows(config) {
  // Normalise
  const normalised = {
    projectType: config.projectType || 'nodejs',
    packageManager: config.packageManager || 'npm',
    deployTarget: config.deployTarget || 'vercel',
    branchFlow: config.branchFlow || 'feature-main',
    checks: Array.isArray(config.checks) ? config.checks : [],
    deployEnvironments: Array.isArray(config.deployEnvironments)
      ? config.deployEnvironments
      : ['production'],
  };

  // Expand "both" shorthand
  if (normalised.deployEnvironments.includes('both')) {
    normalised.deployEnvironments = ['staging', 'production', 'both'];
  }

  // Branch flow 'dev -> staging -> main' should include staging deployment support
  if (normalised.branchFlow === 'dev-staging-main' && !normalised.deployEnvironments.includes('staging')) {
    normalised.deployEnvironments = ['staging', ...normalised.deployEnvironments.filter((env) => env !== 'both')];
  }

  const files = {};

  // 1. CI workflow
  files['.github/workflows/ci.yml'] = generateCI(normalised);

  // 2. Staging deploy
  const stagingYml = generateDeployStaging(normalised);
  if (stagingYml) {
    files['.github/workflows/deploy-staging.yml'] = stagingYml;
  }

  // 3. Production deploy
  const productionYml = generateDeployProduction(normalised);
  if (productionYml) {
    files['.github/workflows/deploy-production.yml'] = productionYml;
  }

  // 4. .env.example
  files['.env.example'] = generateEnvExample(normalised);

  // 5. README deployment notes (returned as a virtual file for display)
  files['DEPLOYMENT_NOTES.md'] = generateDeploymentNotes(normalised);

  return files;
}

/**
 * Generates inline deployment notes / README section.
 */
function generateDeploymentNotes(config) {
  const { projectType, deployTarget, deployEnvironments, branchFlow, checks } = config;

  const deployTargetNames = {
    vercel: 'Vercel',
    render: 'Render',
    aws: 'AWS (S3 + CloudFront)',
    digitalocean: 'DigitalOcean App Platform',
    vps: 'VPS via SSH',
  };

  const projectNames = {
    nextjs: 'Next.js',
    react: 'React',
    nodejs: 'Node.js',
    laravel: 'Laravel',
    wordpress: 'WordPress',
    'shopify-theme': 'Shopify Theme',
    nestjs: 'NestJS',
  };

  const branchFlowDesc = branchFlow === 'dev-staging-main'
    ? '`dev` → `staging` → `main`'
    : '`feature/*` → `main`';

  const secretsTable = getSecretsTable(deployTarget, deployEnvironments);

  const checksDesc = checks.length > 0
    ? checks.map(c => ({
        lint: '`npm run lint` — ESLint / PHP CS Fixer',
        typecheck: '`npm run typecheck` — TypeScript type checking',
        test: 'Unit tests — Jest / PHPUnit',
        build: '`npm run build` — Production build',
        lighthouse: 'Lighthouse CI — performance audits',
        playwright: 'Playwright — end-to-end browser tests',
      }[c] || c)).join('\n- ')
    : 'None selected';

  return `# CI/CD Deployment Notes

Generated by [CI/CD Pipeline Generator](https://github.com/your-org/cicd-pipeline-generator)

## Project Configuration

| Setting | Value |
|---------|-------|
| Project type | ${projectNames[projectType] || projectType} |
| Deploy target | ${deployTargetNames[deployTarget] || deployTarget} |
| Branch flow | ${branchFlowDesc} |
| Environments | ${deployEnvironments.filter(e => e !== 'both').join(', ')} |

## Checks Included

- ${checksDesc}

## Workflow Files

| File | Trigger | Purpose |
|------|---------|---------|
| \`.github/workflows/ci.yml\` | Every PR | Lint, test, build |
${deployEnvironments.includes('staging') || deployEnvironments.includes('both') ? `| \`.github/workflows/deploy-staging.yml\` | Push to \`staging\` | Deploy to staging environment |` : ''}
${deployEnvironments.includes('production') || deployEnvironments.includes('both') ? `| \`.github/workflows/deploy-production.yml\` | Push to \`main\` | Deploy to production + create release |` : ''}

## How to use these files

1. Add the workflow files to your repository under \`.github/workflows/\`.
2. Copy \`.env.example\` to \`.env\` and replace placeholder values with your real configuration.
3. Create the branches used by your flow: \`dev\`, \`staging\`, and \`main\` if you selected the multi-stage branch strategy.
4. Add the required secrets in GitHub: **Settings → Secrets and variables → Actions**.
5. Commit and push the workflow files to GitHub.
6. Open a pull request or push to the deployment branch to trigger the pipeline.
7. Watch the Actions tab to confirm each job passes.

## How to verify everything works locally

- Run \`npm ci\`
- Run \`npm run lint\`
- Run \`npm run test\`
- Run \`npm run build\`

If the workflow still fails after these checks, review the job logs in GitHub Actions and compare the error messages with the generated deployment notes.

## Required GitHub Secrets

Add these in **Settings → Secrets and variables → Actions** on your repository:

${secretsTable}

## Branch Setup

${branchFlow === 'dev-staging-main' ? `
### dev → staging → main flow

1. Feature branches merge into \`dev\`
2. When ready for testing, merge \`dev\` into \`staging\` — triggers staging deploy
3. After QA, merge \`staging\` into \`main\` — triggers production deploy + creates GitHub Release
` : `
### feature → main flow

1. Create feature branches from \`main\`
2. Open a PR — CI checks run automatically
3. Merge PR into \`main\` — triggers production deploy + creates GitHub Release
`}

## First-Time Setup Checklist

- [ ] Add all required secrets listed above to GitHub repository settings
- [ ] Create \`staging\` branch (if using staging environment)
- [ ] Set up GitHub Environments: **Settings → Environments** — add \`staging\` and \`production\`
- [ ] Enable required status checks on protected branches
- [ ] Copy \`.env.example\` to \`.env\` on your server(s) and fill in values
- [ ] Test the CI workflow by opening a draft PR

## Deployment Target Notes

${getDeployTargetNotes(deployTarget)}
`;
}

function getSecretsTable(deployTarget, deployEnvironments) {
  const hasStaging = deployEnvironments.includes('staging') || deployEnvironments.includes('both');
  const hasProd = deployEnvironments.includes('production') || deployEnvironments.includes('both');

  const rows = {
    vercel: [
      ['`VERCEL_TOKEN`', 'Vercel API token', 'vercel.com → Account Settings → Tokens'],
      ['`VERCEL_ORG_ID`', 'Vercel organisation ID', 'Run `vercel link` and check `.vercel/project.json`'],
      ['`VERCEL_PROJECT_ID`', 'Vercel project ID', 'Run `vercel link` and check `.vercel/project.json`'],
    ],
    render: [
      ['`RENDER_DEPLOY_HOOK_URL`', 'Render deploy hook URL', 'Render dashboard → Service → Settings → Deploy Hooks'],
      ...(hasStaging ? [['`RENDER_DEPLOY_HOOK_URL_STAGING`', 'Staging deploy hook URL', 'Separate staging service deploy hook']] : []),
    ],
    aws: [
      ['`AWS_ACCESS_KEY_ID`', 'IAM access key ID', 'AWS Console → IAM → Users → Security credentials'],
      ['`AWS_SECRET_ACCESS_KEY`', 'IAM secret access key', 'Generated alongside access key ID'],
      ['`AWS_REGION`', 'AWS region', 'e.g. `us-east-1`'],
      ...(hasProd ? [
        ['`S3_BUCKET_PRODUCTION`', 'Production S3 bucket name', 'Your S3 bucket for production'],
        ['`CLOUDFRONT_DISTRIBUTION_ID_PRODUCTION`', 'Production CloudFront distribution ID', 'AWS Console → CloudFront'],
        ['`CLOUDFRONT_DOMAIN_PRODUCTION`', 'Production CloudFront domain', 'e.g. `https://d123.cloudfront.net`'],
      ] : []),
      ...(hasStaging ? [
        ['`S3_BUCKET_STAGING`', 'Staging S3 bucket name', 'Your S3 bucket for staging'],
        ['`CLOUDFRONT_DISTRIBUTION_ID_STAGING`', 'Staging CloudFront distribution ID', 'AWS Console → CloudFront'],
      ] : []),
    ],
    digitalocean: [
      ['`DIGITALOCEAN_ACCESS_TOKEN`', 'DigitalOcean API token', 'DigitalOcean → API → Generate New Token (read+write)'],
      ...(hasProd ? [['`DO_APP_NAME_PRODUCTION`', 'App Platform app name (prod)', 'DigitalOcean App Platform dashboard']] : []),
      ...(hasStaging ? [['`DO_APP_NAME_STAGING`', 'App Platform app name (staging)', 'DigitalOcean App Platform dashboard']] : []),
    ],
    vps: [
      ['`SSH_USERNAME`', 'SSH user on VPS', 'Usually `deploy` or `ubuntu`'],
      ['`SSH_PRIVATE_KEY`', 'SSH private key (entire file)', 'Paste contents of `~/.ssh/id_rsa` or your deploy key'],
      ...(hasProd ? [['`SSH_HOST_PRODUCTION`', 'Production server IP/hostname', 'Your VPS public IP or domain']] : []),
      ...(hasStaging ? [['`SSH_HOST_STAGING`', 'Staging server IP/hostname', 'Your staging VPS public IP or domain']] : []),
    ],
  };

  const targetRows = rows[deployTarget] || [];
  const header = '| Secret | Description | Where to find it |\n|--------|-------------|------------------|';
  const body = targetRows.map(([secret, desc, where]) => `| ${secret} | ${desc} | ${where} |`).join('\n');
  return `${header}\n${body}`;
}

function getDeployTargetNotes(deployTarget) {
  switch (deployTarget) {
    case 'vercel':
      return `### Vercel

- Run \`npm i -g vercel && vercel login && vercel link\` locally to generate the project config
- The generated \`.vercel/project.json\` contains \`orgId\` and \`projectId\`
- Staging deploys create preview URLs; production deploys update the main domain
- Set environment variables in Vercel dashboard per environment`;

    case 'render':
      return `### Render

- Create separate Render services for staging and production
- Each service has its own deploy hook URL in **Settings → Deploy Hooks**
- Render auto-detects the framework and build command
- Set environment variables directly in the Render dashboard`;

    case 'aws':
      return `### AWS S3 + CloudFront

- Create an IAM user with \`s3:PutObject\`, \`s3:DeleteObject\`, \`cloudfront:CreateInvalidation\` permissions
- Enable static website hosting on your S3 bucket
- Create a CloudFront distribution pointing to your S3 bucket
- Use separate buckets/distributions for staging and production
- HTML files use \`no-cache\` to ensure fresh content; assets use \`immutable\` caching`;

    case 'digitalocean':
      return `### DigitalOcean App Platform

- Connect your GitHub repository in the DigitalOcean App Platform dashboard
- Create separate apps for staging and production
- The workflow triggers a redeploy — App Platform handles the build
- Set environment variables in the App Platform dashboard per component`;

    case 'vps':
      return `### VPS SSH Deploy

- Create a \`deploy\` user on your VPS with restricted shell access
- Generate a dedicated SSH keypair: \`ssh-keygen -t ed25519 -C "github-actions-deploy"\`
- Add the public key to \`~/.ssh/authorized_keys\` on your VPS
- Ensure \`pm2\` is installed globally: \`npm i -g pm2\`
- The deploy script: pulls latest code, installs deps, builds, and restarts the process`;

    default:
      return '';
  }
}

module.exports = { generateWorkflows };
